### PR TITLE
Enable rocprofv1 for additional socs

### PR DESCRIPTION
**Pull request by xuchen-amd**
Enable rocprofv1 for soc_gfx940.py, soc_gfx941.py, soc_gfx942.py.
Jira Tracking: https://ontrack-internal.amd.com/browse/SWDEV-474924

### CODE REVIEW

**Comment by coleramos425** [comment]
@xuchen-amd can you modify the PR to merge into `dev` branch instead of `main`?

**Comment by xuchen-amd** [comment]
reopening PR.

**Comment by coleramos425** [comment]
@xuchen-amd looks like the PR is reporting 316 files changed. This is likely because your branch is out of date with the base. Could you update your branch with a rebase?

**Comment by coleramos425** [comment]
@xuchen-amd I've sent you a short meeting request via Outlook. A quick discussion should be the fastest solution.

**Pull request merged**
