### PR TITLE
determinstic ordering of perfmon (#332)

### PR DESCRIPTION
**Pull request by skyreflectedinmirrors**

### CODE REVIEW

**Comment by skyreflectedinmirrors** [comment]
Still need some discussion on the best way to handle it internally.

**Comment by coleramos425** [comment]
Looks good to me. The only thing I need is a formatting commit,
```console
$ python3 -m install -U black
$ cd omniperf && black .
```

**Comment by skyreflectedinmirrors** [comment]
Let's discuss during our regular call tomorrow.  Theoretically, we probably don't even want to merge separate pmc lines _unless_ they both fit to address this, but I'm worried that will blow up the number of replays.

**Review by coleramos425 — APPROVED** [review]
LGTM. Thanks, Nick!

**Comment by coleramos425** [comment]
And.... I found an issue with rocprofv1 🙃. I suspect this is because we removed:

```python
if counter not in pmc_list[IP_block]:
    pmc_list[IP_block].append(counter)
```

ROCm Module: rocm/6.0.2
Omniperf Version: latest dev

```bash
|-> [rocprof] SQ_CYCLES, SQ_BUSY_CYCLES, SQ_WAVES, SQ_CYCLES, SQ_BUSY_CYCLES, SQ_WAVES, SQ_CYCLES, SQ_BUSY_CYCLES, GRBM_COUNT, GRBM_GUI_ACTIVE, TCP_GATE_EN1_sum, TCP_GATE_EN2_sum, TCP_TD_TCP_STALL_CYCLES_sum, TCP_TCR_TCP_STALL_CYCLES_sum, TA_TA_BUSY_sum, TA_BUFFER_WAVEFRONTS_sum, TD_TD_BUSY_sum, TD_TC_STALL_sum, SPI_CSN_WINDOW_VALID, SPI_CSN_BUSY, CPC_CPC_STAT_BUSY, CPC_CPC_STAT_IDLE, CPF_CPF_STAT_BUSY, CPF_CPF_STAT_STALL, TCC_CYCLE_sum, TCC_BUSY_sum, TCC_PROBE_sum, TCC_PROBE_ALL_sum
   |-> [rocprof] ------------------------ Device specifications ------------------------
   |-> [rocprof] Device:              AMD Instinct MI210
   |-> [rocprof] CUDA driver version: 60032.831
   |-> [rocprof] GPU clock rate:      1700 MHz
   |-> [rocprof] WarpSize:            64
   |-> [rocprof] L2 cache size:       8192 KB
   |-> [rocprof] Total global mem:    65520 MB
   |-> [rocprof] Total SPs:           13312 (104 MPs x 128 SPs/MP)
   |-> [rocprof] Compute throughput:  45260.80 GFlops (theoretical single precision FMAs)
   |-> [rocprof] Memory bandwidth:    1638.40 GB/sec
   |-> [rocprof] -----------------------------------------------------------------------
   |-> [rocprof] Total GPU memory 68702699520, free 68625104896
   |-> [rocprof] Buffer size:          256MB
   |-> [rocprof] Trade-off type:       compute with global memory (block strided)
   |-> [rocprof] Elements per thread:  8
   |-> [rocprof] Thread fusion degree: 1
   |-> [rocprof] Initialize(), input metric 'SQ_CYCLES' is registered more then once
   |-> [rocprof] Error: Context Create failed
   |-> [rocprof] /opt/rocm-6.0.2/bin/rocprof: line 334: 589364 Aborted                 (core dumped) ""/home/colramos/mixbench-hip""
   |-> [rocprof] File '/home/colramos/GitHub/omniperf/workloads/mixbench/MI200/pmc_perf_0.csv' is generating
   |-> [rocprof]
ERROR Profiling execution failed.
```
[log.txt](https://github.com/ROCm/omniperf/files/14805430/log.txt)

**Pull request merged**
